### ISSUE TITLE
tensorflow/keras requirements

### ISSUE THREAD

**Issue by simra** [taoqi98/FedNewsRec#10]
Hi, could you add or share a requirements.txt file? It looks like the code needs tensorflow 1.x and I'm having a hard time finding the right keras version that works with it.

**Comment by taoqi98** [comment]
Hi, thank you for your attention on our work. Our codes have included a requirement file (path: code/requirement.txt). You can refer to this file for installing tf and keras.

**Comment by simra** [comment]
Sorry, I missed this. Thanks!
