### ISSUE TITLE
InvalidArgumentError

### ISSUE THREAD

**Issue by cqliang1995** [taoqi98/FedNewsRec#4]
when I run your code，I got that：

tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension must be 5 but is 4 for 'attention_1/transpose_7' (op: 'Transpose') with input shapes: [?,20,?,20,?], [4].

**Comment by taoqi98** [comment]
This is caused by the unmatched versions of tensor-flow and Keras. You can use tensorflow-gpu == 1.13.0 and keras == 2.2.4 to run our codes.
