### ISSUE TITLE
关于对多个client上传梯度g的aggregate方式

### ISSUE THREAD

**Issue by cqliang1995** [taoqi98/FedNewsRec#5]
您好！这是一个关于本篇论文里的server端对多个client上传的梯度g进行aggregate公式的问题：

我看到论文公式里server会用到各个client用户的behaviors对梯度进行聚合，这是不是意味着client还需要上传用户行为，不然无法执行公式里描述的梯度聚合。

这样岂不是违背了保护隐私的初衷？我是一个正在入门的小白，应该是我没有理解正确才会有这样的疑问，还请您指点一下。

ps：关于我说的公式，是论文里标号为（6）的那个梯度聚合公式。

**Comment by TaoHaoTian** [comment]
cqliang1995 这位兄弟最近我也在学习这个项目，想请教你一下关于这篇论文的代码复现问题。

**Comment by TaoHaoTian** [comment]
cqliang1995

**Comment by TaoHaoTian** [comment]
cqliang1995这位兄弟，最近我也在学习这篇论文和代码，想请教您关于这篇论文的代码复现问题。qq:2250324130。还请不吝赐教

**Comment by cqliang1995** [comment]
幸会幸会，我也是在学习，其实我什么都不懂，以小白身份入门，还望赐教。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年4月5日 20:47
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [JulySinceAndrew/FedNewsRec-EMNLP-Findings-2020] 关于对多个client上传梯度g的aggregate方式 (#5)


cqliang1995这位兄弟，最近我也在学习这篇论文和代码，想请教您关于这篇论文的代码复现问题。qq:2250324130。还请不吝赐教

―

**Comment by taoqi98** [comment]
Thanks for the great question. In Eq.(6) in our paper, we only need to up load the number of behaviors (i.e., |B_u|), instead of behavior set (i.e., B_u) to the server.
